"""Recreated models

Revision ID: e95c387ee49a
Revises: 7af50a8df6bd
Create Date: 2025-04-08 18:09:04.057703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e95c387ee49a'
down_revision: Union[str, None] = '7af50a8df6bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('files_bid_id_fkey', 'files', type_='foreignkey')
    op.create_foreign_key(None, 'files', 'bid', ['bid_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.create_foreign_key('files_bid_id_fkey', 'files', 'task', ['bid_id'], ['id'])
    # ### end Alembic commands ###
