"""Recreated models

Revision ID: 2fff58de8ceb
Revises: e95c387ee49a
Create Date: 2025-04-12 14:33:42.116448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2fff58de8ceb'
down_revision: Union[str, None] = 'e95c387ee49a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bid', 'is_deleted')
    op.alter_column('task', 'status',
               existing_type=postgresql.ENUM('NEW', 'IN_WORK', 'COMPLETED', 'CANCELED', 'ON_HOLD', name='statusenum'),
               nullable=True)
    op.drop_constraint('task_product_id_fkey', 'task', type_='foreignkey')
    op.drop_constraint('task_material_id_fkey', 'task', type_='foreignkey')
    op.create_foreign_key('task_product_id_fkey', 'task', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('task_material_id_fkey', 'task', 'material', ['material_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_product_id_fkey', 'task', type_='foreignkey')
    op.drop_constraint('task_material_id_fkey', 'task', type_='foreignkey')
    op.create_foreign_key('task_material_id_fkey', 'task', 'material', ['material_id'], ['id'])
    op.create_foreign_key('task_product_id_fkey', 'task', 'product', ['product_id'], ['id'])
    op.alter_column('task', 'status',
               existing_type=postgresql.ENUM('NEW', 'IN_WORK', 'COMPLETED', 'CANCELED', 'ON_HOLD', name='statusenum'),
               nullable=False)
    op.add_column('bid', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
