"""Recreated models

Revision ID: 7af50a8df6bd
Revises: 84560ef83ebb
Create Date: 2025-04-08 17:55:02.103677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7af50a8df6bd'
down_revision: Union[str, None] = '84560ef83ebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cassette', sa.Column('cassette_type', sa.Enum('KZT_STD', 'KOT_STD', 'KOTVO', 'KZT', 'KOT', 'OTHER', name='cassettetypeenum'), nullable=False))
    op.drop_column('cassette', 'cassette_type_id')
    op.drop_column('comment', 'is_deleted')
    op.add_column('files', sa.Column('bid_id', sa.Integer(), nullable=False))
    op.drop_constraint('files_task_id_fkey', 'files', type_='foreignkey')
    op.create_foreign_key(None, 'files', 'task', ['bid_id'], ['id'])
    op.drop_column('files', 'task_id')
    op.drop_column('files', 'is_deleted')
    op.add_column('material', sa.Column('form', sa.Enum('SHEET', 'COIL', 'STRIP', name='materialformenum'), nullable=False))
    op.add_column('material', sa.Column('type', sa.Enum('ALUMINIUM', 'STEEL', 'STAINLESS_STEEL', 'ZINC', 'POLYMER', name='materialtypeenum'), nullable=False))
    op.add_column('material', sa.Column('thickness', sa.Enum('ZERO_FIVE', 'ZERO_SEVEN', 'ONE', 'ONE_TWO', 'ONE_FIVE', 'TWO', 'THREE', name='materialthicknessenum'), nullable=False))
    op.drop_column('material', 'form_id')
    op.drop_column('material', 'thickness_id')
    op.drop_column('material', 'type_id')
    op.add_column('task', sa.Column('urgency', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='urgencyenum'), nullable=False))
    op.add_column('task', sa.Column('status', sa.Enum('NEW', 'IN_WORK', 'COMPLETED', 'CANCELED', 'ON_HOLD', name='statusenum'), nullable=False))
    op.drop_column('task', 'is_deleted')
    op.drop_column('task', 'status_id')
    op.drop_column('task', 'urgency_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('urgency_id', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='urgencyenum'), autoincrement=False, nullable=False))
    op.add_column('task', sa.Column('status_id', postgresql.ENUM('NEW', 'IN_WORK', 'COMPLETED', 'CANCELED', 'ON_HOLD', name='statusenum'), autoincrement=False, nullable=False))
    op.add_column('task', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('task', 'status')
    op.drop_column('task', 'urgency')
    op.add_column('material', sa.Column('type_id', postgresql.ENUM('ALUMINIUM', 'STEEL', 'STAINLESS_STEEL', 'ZINC', 'POLYMER', name='materialtypeenum'), autoincrement=False, nullable=False))
    op.add_column('material', sa.Column('thickness_id', postgresql.ENUM('ZERO_FIVE', 'ZERO_SEVEN', 'ONE', 'ONE_TWO', 'ONE_FIVE', 'TWO', 'THREE', name='materialthicknessenum'), autoincrement=False, nullable=False))
    op.add_column('material', sa.Column('form_id', postgresql.ENUM('SHEET', 'COIL', 'STRIP', name='materialformenum'), autoincrement=False, nullable=False))
    op.drop_column('material', 'thickness')
    op.drop_column('material', 'type')
    op.drop_column('material', 'form')
    op.add_column('files', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('files', sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.create_foreign_key('files_task_id_fkey', 'files', 'task', ['task_id'], ['id'])
    op.drop_column('files', 'bid_id')
    op.add_column('comment', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('cassette', sa.Column('cassette_type_id', postgresql.ENUM('KZT_STD', 'KOT_STD', 'KOTVO', 'KZT', 'KOT', 'OTHER', name='cassettetypeenum'), autoincrement=False, nullable=False))
    op.drop_column('cassette', 'cassette_type')
    # ### end Alembic commands ###
